name: Electron UI Tests

on:
  workflow_dispatch:
    inputs:
      specs:
        description: 'Spec file'
        default: cypress/integration/*

jobs:
 
 ui-tests-electron:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.17.0-chrome91-ff89
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'UI Tests - Electron'
        uses: cypress-io/github-action@v2
        with:
          # we have already installed all dependencies above
          install-command: yarn install
          wait-on: ${{ secrets.BASE_URL }}
          wait-on-timeout: 120
          browser: firefox
          record: true
          parallel: true
          group: 'UI - Electron'
          spec: ${{ github.event.inputs.specs }}
        env:
          TZ: America/Sao_Paulo
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Videos
        uses: actions/upload-artifact@v2.3.1
        if: always()
        with:
          name: Electron Videos
          path: cypress/videos

      - name: Upload Screenshots
        uses: actions/upload-artifact@v2.3.1
        if: always()
        with:
          name: Electron Screenshots
          path: cypress/screenshots
